# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hydir_v2_pb2 as hydir__v2__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hydir_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HydirV2Stub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/hydir.v2.HydirV2/Discover',
                request_serializer=hydir__v2__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.DiscoverReply.FromString,
                _registered_method=True)
        self.GetRegion = channel.unary_unary(
                '/hydir.v2.HydirV2/GetRegion',
                request_serializer=hydir__v2__pb2.RegionRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.LiftRegion = channel.unary_unary(
                '/hydir.v2.HydirV2/LiftRegion',
                request_serializer=hydir__v2__pb2.RegionRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.DecompileRegion = channel.unary_unary(
                '/hydir.v2.HydirV2/DecompileRegion',
                request_serializer=hydir__v2__pb2.RegionRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.CompilePatch = channel.unary_unary(
                '/hydir.v2.HydirV2/CompilePatch',
                request_serializer=hydir__v2__pb2.PatchRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.ApplyPatch = channel.unary_unary(
                '/hydir.v2.HydirV2/ApplyPatch',
                request_serializer=hydir__v2__pb2.PatchRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.MutationReply.FromString,
                _registered_method=True)
        self.VerifyPatch = channel.unary_unary(
                '/hydir.v2.HydirV2/VerifyPatch',
                request_serializer=hydir__v2__pb2.VerifyPatchRequest.SerializeToString,
                response_deserializer=hydir__v2__pb2.VerificationReply.FromString,
                _registered_method=True)


class HydirV2Servicer:
    """Missing associated documentation comment in .proto file."""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiftRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecompileRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompilePatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HydirV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=hydir__v2__pb2.DiscoverRequest.FromString,
                    response_serializer=hydir__v2__pb2.DiscoverReply.SerializeToString,
            ),
            'GetRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegion,
                    request_deserializer=hydir__v2__pb2.RegionRequest.FromString,
                    response_serializer=hydir__v2__pb2.ArtifactReply.SerializeToString,
            ),
            'LiftRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.LiftRegion,
                    request_deserializer=hydir__v2__pb2.RegionRequest.FromString,
                    response_serializer=hydir__v2__pb2.ArtifactReply.SerializeToString,
            ),
            'DecompileRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.DecompileRegion,
                    request_deserializer=hydir__v2__pb2.RegionRequest.FromString,
                    response_serializer=hydir__v2__pb2.ArtifactReply.SerializeToString,
            ),
            'CompilePatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CompilePatch,
                    request_deserializer=hydir__v2__pb2.PatchRequest.FromString,
                    response_serializer=hydir__v2__pb2.ArtifactReply.SerializeToString,
            ),
            'ApplyPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPatch,
                    request_deserializer=hydir__v2__pb2.PatchRequest.FromString,
                    response_serializer=hydir__v2__pb2.MutationReply.SerializeToString,
            ),
            'VerifyPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPatch,
                    request_deserializer=hydir__v2__pb2.VerifyPatchRequest.FromString,
                    response_serializer=hydir__v2__pb2.VerificationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydir.v2.HydirV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydir.v2.HydirV2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HydirV2:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/Discover',
            hydir__v2__pb2.DiscoverRequest.SerializeToString,
            hydir__v2__pb2.DiscoverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/GetRegion',
            hydir__v2__pb2.RegionRequest.SerializeToString,
            hydir__v2__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiftRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/LiftRegion',
            hydir__v2__pb2.RegionRequest.SerializeToString,
            hydir__v2__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecompileRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/DecompileRegion',
            hydir__v2__pb2.RegionRequest.SerializeToString,
            hydir__v2__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompilePatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/CompilePatch',
            hydir__v2__pb2.PatchRequest.SerializeToString,
            hydir__v2__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/ApplyPatch',
            hydir__v2__pb2.PatchRequest.SerializeToString,
            hydir__v2__pb2.MutationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v2.HydirV2/VerifyPatch',
            hydir__v2__pb2.VerifyPatchRequest.SerializeToString,
            hydir__v2__pb2.VerificationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
