# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hydir_v3_pb2 as hydir__v3__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hydir_v3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HydirV3Stub:
    """Native whole-program analysis contract. v1 and v2 remain available for
    compatibility; this service never requires an external decompiler.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/hydir.v3.HydirV3/Discover',
                request_serializer=hydir__v3__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.DiscoverReply.FromString,
                _registered_method=True)
        self.StartProgramAnalysis = channel.unary_unary(
                '/hydir.v3.HydirV3/StartProgramAnalysis',
                request_serializer=hydir__v3__pb2.StartProgramAnalysisRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.JobReply.FromString,
                _registered_method=True)
        self.GetAnalysisJob = channel.unary_unary(
                '/hydir.v3.HydirV3/GetAnalysisJob',
                request_serializer=hydir__v3__pb2.JobRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.JobReply.FromString,
                _registered_method=True)
        self.CancelAnalysisJob = channel.unary_unary(
                '/hydir.v3.HydirV3/CancelAnalysisJob',
                request_serializer=hydir__v3__pb2.JobRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.JobReply.FromString,
                _registered_method=True)
        self.StreamAnalysisEvents = channel.unary_stream(
                '/hydir.v3.HydirV3/StreamAnalysisEvents',
                request_serializer=hydir__v3__pb2.JobEventRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.JobEvent.FromString,
                _registered_method=True)
        self.GetProgramArtifact = channel.unary_unary(
                '/hydir.v3.HydirV3/GetProgramArtifact',
                request_serializer=hydir__v3__pb2.ProgramArtifactRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.UpdateAnalystFact = channel.unary_unary(
                '/hydir.v3.HydirV3/UpdateAnalystFact',
                request_serializer=hydir__v3__pb2.AnalystFactRequest.SerializeToString,
                response_deserializer=hydir__v3__pb2.MutationReply.FromString,
                _registered_method=True)


class HydirV3Servicer:
    """Native whole-program analysis contract. v1 and v2 remain available for
    compatibility; this service never requires an external decompiler.
    """

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartProgramAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysisJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAnalysisJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalysisEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgramArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAnalystFact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HydirV3Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=hydir__v3__pb2.DiscoverRequest.FromString,
                    response_serializer=hydir__v3__pb2.DiscoverReply.SerializeToString,
            ),
            'StartProgramAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProgramAnalysis,
                    request_deserializer=hydir__v3__pb2.StartProgramAnalysisRequest.FromString,
                    response_serializer=hydir__v3__pb2.JobReply.SerializeToString,
            ),
            'GetAnalysisJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysisJob,
                    request_deserializer=hydir__v3__pb2.JobRequest.FromString,
                    response_serializer=hydir__v3__pb2.JobReply.SerializeToString,
            ),
            'CancelAnalysisJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAnalysisJob,
                    request_deserializer=hydir__v3__pb2.JobRequest.FromString,
                    response_serializer=hydir__v3__pb2.JobReply.SerializeToString,
            ),
            'StreamAnalysisEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnalysisEvents,
                    request_deserializer=hydir__v3__pb2.JobEventRequest.FromString,
                    response_serializer=hydir__v3__pb2.JobEvent.SerializeToString,
            ),
            'GetProgramArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgramArtifact,
                    request_deserializer=hydir__v3__pb2.ProgramArtifactRequest.FromString,
                    response_serializer=hydir__v3__pb2.ArtifactReply.SerializeToString,
            ),
            'UpdateAnalystFact': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAnalystFact,
                    request_deserializer=hydir__v3__pb2.AnalystFactRequest.FromString,
                    response_serializer=hydir__v3__pb2.MutationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydir.v3.HydirV3', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydir.v3.HydirV3', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HydirV3:
    """Native whole-program analysis contract. v1 and v2 remain available for
    compatibility; this service never requires an external decompiler.
    """

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v3.HydirV3/Discover',
            hydir__v3__pb2.DiscoverRequest.SerializeToString,
            hydir__v3__pb2.DiscoverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartProgramAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v3.HydirV3/StartProgramAnalysis',
            hydir__v3__pb2.StartProgramAnalysisRequest.SerializeToString,
            hydir__v3__pb2.JobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalysisJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v3.HydirV3/GetAnalysisJob',
            hydir__v3__pb2.JobRequest.SerializeToString,
            hydir__v3__pb2.JobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAnalysisJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v3.HydirV3/CancelAnalysisJob',
            hydir__v3__pb2.JobRequest.SerializeToString,
            hydir__v3__pb2.JobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAnalysisEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hydir.v3.HydirV3/StreamAnalysisEvents',
            hydir__v3__pb2.JobEventRequest.SerializeToString,
            hydir__v3__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgramArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v3.HydirV3/GetProgramArtifact',
            hydir__v3__pb2.ProgramArtifactRequest.SerializeToString,
            hydir__v3__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAnalystFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v3.HydirV3/UpdateAnalystFact',
            hydir__v3__pb2.AnalystFactRequest.SerializeToString,
            hydir__v3__pb2.MutationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
