# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hydir_pb2 as hydir__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hydir_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HydirStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/hydir.v1.Hydir/Discover',
                request_serializer=hydir__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=hydir__pb2.DiscoverReply.FromString,
                _registered_method=True)
        self.GetSource = channel.unary_unary(
                '/hydir.v1.Hydir/GetSource',
                request_serializer=hydir__pb2.SourceRequest.SerializeToString,
                response_deserializer=hydir__pb2.SourceReply.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/hydir.v1.Hydir/CreateProject',
                request_serializer=hydir__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=hydir__pb2.ProjectReply.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/hydir.v1.Hydir/GetProject',
                request_serializer=hydir__pb2.ProjectRequest.SerializeToString,
                response_deserializer=hydir__pb2.ProjectReply.FromString,
                _registered_method=True)
        self.UploadBinary = channel.unary_unary(
                '/hydir.v1.Hydir/UploadBinary',
                request_serializer=hydir__pb2.UploadBinaryRequest.SerializeToString,
                response_deserializer=hydir__pb2.ProjectReply.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/hydir.v1.Hydir/Inspect',
                request_serializer=hydir__pb2.ProjectRequest.SerializeToString,
                response_deserializer=hydir__pb2.JsonReply.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/hydir.v1.Hydir/Analyze',
                request_serializer=hydir__pb2.ProjectRequest.SerializeToString,
                response_deserializer=hydir__pb2.JsonReply.FromString,
                _registered_method=True)
        self.RecoverCfg = channel.unary_unary(
                '/hydir.v1.Hydir/RecoverCfg',
                request_serializer=hydir__pb2.FunctionRequest.SerializeToString,
                response_deserializer=hydir__pb2.JsonReply.FromString,
                _registered_method=True)
        self.Lift = channel.unary_unary(
                '/hydir.v1.Hydir/Lift',
                request_serializer=hydir__pb2.FunctionRequest.SerializeToString,
                response_deserializer=hydir__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.Decompile = channel.unary_unary(
                '/hydir.v1.Hydir/Decompile',
                request_serializer=hydir__pb2.FunctionRequest.SerializeToString,
                response_deserializer=hydir__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.Transform = channel.unary_unary(
                '/hydir.v1.Hydir/Transform',
                request_serializer=hydir__pb2.TransformRequest.SerializeToString,
                response_deserializer=hydir__pb2.TransformReply.FromString,
                _registered_method=True)
        self.ApplyPatch = channel.unary_unary(
                '/hydir.v1.Hydir/ApplyPatch',
                request_serializer=hydir__pb2.PatchRequest.SerializeToString,
                response_deserializer=hydir__pb2.PatchReply.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/hydir.v1.Hydir/GetArtifact',
                request_serializer=hydir__pb2.ArtifactRequest.SerializeToString,
                response_deserializer=hydir__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.StartLiftJob = channel.unary_unary(
                '/hydir.v1.Hydir/StartLiftJob',
                request_serializer=hydir__pb2.StartLiftJobRequest.SerializeToString,
                response_deserializer=hydir__pb2.JobReply.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/hydir.v1.Hydir/GetJob',
                request_serializer=hydir__pb2.JobRequest.SerializeToString,
                response_deserializer=hydir__pb2.JobReply.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/hydir.v1.Hydir/CancelJob',
                request_serializer=hydir__pb2.JobRequest.SerializeToString,
                response_deserializer=hydir__pb2.JobReply.FromString,
                _registered_method=True)
        self.StreamJobEvents = channel.unary_stream(
                '/hydir.v1.Hydir/StreamJobEvents',
                request_serializer=hydir__pb2.JobEventRequest.SerializeToString,
                response_deserializer=hydir__pb2.JobEvent.FromString,
                _registered_method=True)


class HydirServicer:
    """Missing associated documentation comment in .proto file."""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverCfg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lift(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decompile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartLiftJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HydirServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=hydir__pb2.DiscoverRequest.FromString,
                    response_serializer=hydir__pb2.DiscoverReply.SerializeToString,
            ),
            'GetSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSource,
                    request_deserializer=hydir__pb2.SourceRequest.FromString,
                    response_serializer=hydir__pb2.SourceReply.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=hydir__pb2.CreateProjectRequest.FromString,
                    response_serializer=hydir__pb2.ProjectReply.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=hydir__pb2.ProjectRequest.FromString,
                    response_serializer=hydir__pb2.ProjectReply.SerializeToString,
            ),
            'UploadBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadBinary,
                    request_deserializer=hydir__pb2.UploadBinaryRequest.FromString,
                    response_serializer=hydir__pb2.ProjectReply.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=hydir__pb2.ProjectRequest.FromString,
                    response_serializer=hydir__pb2.JsonReply.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=hydir__pb2.ProjectRequest.FromString,
                    response_serializer=hydir__pb2.JsonReply.SerializeToString,
            ),
            'RecoverCfg': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverCfg,
                    request_deserializer=hydir__pb2.FunctionRequest.FromString,
                    response_serializer=hydir__pb2.JsonReply.SerializeToString,
            ),
            'Lift': grpc.unary_unary_rpc_method_handler(
                    servicer.Lift,
                    request_deserializer=hydir__pb2.FunctionRequest.FromString,
                    response_serializer=hydir__pb2.ArtifactReply.SerializeToString,
            ),
            'Decompile': grpc.unary_unary_rpc_method_handler(
                    servicer.Decompile,
                    request_deserializer=hydir__pb2.FunctionRequest.FromString,
                    response_serializer=hydir__pb2.ArtifactReply.SerializeToString,
            ),
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=hydir__pb2.TransformRequest.FromString,
                    response_serializer=hydir__pb2.TransformReply.SerializeToString,
            ),
            'ApplyPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPatch,
                    request_deserializer=hydir__pb2.PatchRequest.FromString,
                    response_serializer=hydir__pb2.PatchReply.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=hydir__pb2.ArtifactRequest.FromString,
                    response_serializer=hydir__pb2.ArtifactReply.SerializeToString,
            ),
            'StartLiftJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLiftJob,
                    request_deserializer=hydir__pb2.StartLiftJobRequest.FromString,
                    response_serializer=hydir__pb2.JobReply.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=hydir__pb2.JobRequest.FromString,
                    response_serializer=hydir__pb2.JobReply.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=hydir__pb2.JobRequest.FromString,
                    response_serializer=hydir__pb2.JobReply.SerializeToString,
            ),
            'StreamJobEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobEvents,
                    request_deserializer=hydir__pb2.JobEventRequest.FromString,
                    response_serializer=hydir__pb2.JobEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hydir.v1.Hydir', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hydir.v1.Hydir', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Hydir:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/Discover',
            hydir__pb2.DiscoverRequest.SerializeToString,
            hydir__pb2.DiscoverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/GetSource',
            hydir__pb2.SourceRequest.SerializeToString,
            hydir__pb2.SourceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/CreateProject',
            hydir__pb2.CreateProjectRequest.SerializeToString,
            hydir__pb2.ProjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/GetProject',
            hydir__pb2.ProjectRequest.SerializeToString,
            hydir__pb2.ProjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/UploadBinary',
            hydir__pb2.UploadBinaryRequest.SerializeToString,
            hydir__pb2.ProjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/Inspect',
            hydir__pb2.ProjectRequest.SerializeToString,
            hydir__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/Analyze',
            hydir__pb2.ProjectRequest.SerializeToString,
            hydir__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverCfg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/RecoverCfg',
            hydir__pb2.FunctionRequest.SerializeToString,
            hydir__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/Lift',
            hydir__pb2.FunctionRequest.SerializeToString,
            hydir__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decompile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/Decompile',
            hydir__pb2.FunctionRequest.SerializeToString,
            hydir__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/Transform',
            hydir__pb2.TransformRequest.SerializeToString,
            hydir__pb2.TransformReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/ApplyPatch',
            hydir__pb2.PatchRequest.SerializeToString,
            hydir__pb2.PatchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/GetArtifact',
            hydir__pb2.ArtifactRequest.SerializeToString,
            hydir__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartLiftJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/StartLiftJob',
            hydir__pb2.StartLiftJobRequest.SerializeToString,
            hydir__pb2.JobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/GetJob',
            hydir__pb2.JobRequest.SerializeToString,
            hydir__pb2.JobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hydir.v1.Hydir/CancelJob',
            hydir__pb2.JobRequest.SerializeToString,
            hydir__pb2.JobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hydir.v1.Hydir/StreamJobEvents',
            hydir__pb2.JobEventRequest.SerializeToString,
            hydir__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
