[package]
name = "hydir-patch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hydir-backend = { path = "../hydir-backend" }
hydir-core = { path = "../hydir-core" }
object.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
