[package]
name = "hydir-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hydirctl"
path = "src/main.rs"

[dependencies]
hydir-backend = { path = "../hydir-backend" }
hydir-c = { path = "../hydir-c" }
hydir-patch = { path = "../hydir-patch" }
hydir-transform = { path = "../hydir-transform" }
hydir-recompile = { path = "../hydir-recompile" }
hydir-analysis = { path = "../hydir-analysis" }
hydir-api = { path = "../hydir-api" }
hydir-core = { path = "../hydir-core" }
hydir-irene3 = { path = "../hydir-irene3" }
hydir-project = { path = "../hydir-project" }
object.workspace = true
iced-x86.workspace = true
serde_json.workspace = true
sha2.workspace = true
tonic.workspace = true
tokio.workspace = true
tempfile = "3.23"
