[package]
name = "hydir-recompile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hydir-semantics = { path = "../hydir-semantics" }
object.workspace = true
iced-x86.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3.23"
