[package]
name = "hydir-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hydird"
path = "src/main.rs"

[dependencies]
hydir-api = { path = "../hydir-api" }
hydir-backend = { path = "../hydir-backend" }
hydir-c = { path = "../hydir-c" }
hydir-core = { path = "../hydir-core" }
hydir-interchange = { path = "../hydir-interchange" }
hydir-patch = { path = "../hydir-patch" }
hydir-transform = { path = "../hydir-transform" }
hydir-recompile = { path = "../hydir-recompile" }
hydir-analysis = { path = "../hydir-analysis" }
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
libc.workspace = true
rusqlite.workspace = true
uuid.workspace = true
url.workspace = true
sha2.workspace = true
serde_json.workspace = true
serde.workspace = true
jsonwebtoken.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true

[dev-dependencies]
prost.workspace = true
tempfile = "3.23"
rsa = "0.9.10"
rand = "0.8.5"
