[package]
name = "hydir-ghidra-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hydir-backend = { path = "../hydir-backend" }
hydir-ir = { path = "../hydir-ir" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3.23"
