[package]
name = "hydir-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hydir"
path = "src/main.rs"

[dependencies]
hydir-backend = { path = "../hydir-backend" }
hydir-c = { path = "../hydir-c" }
hydir-analysis = { path = "../hydir-analysis" }
hydir-decompile = { path = "../hydir-decompile" }
hydir-ir = { path = "../hydir-ir" }
hydir-core = { path = "../hydir-core" }
hydir-project = { path = "../hydir-project" }
hydir-model = { path = "../hydir-model" }
hydir-hlc = { path = "../hydir-hlc" }
hydir-api = { path = "../hydir-api" }
hydir-transform = { path = "../hydir-transform" }
hydir-recompile = { path = "../hydir-recompile" }
hydir-patch = { path = "../hydir-patch" }
eframe.workspace = true
egui_graph.workspace = true
egui_graph_egui.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tonic.workspace = true
uuid.workspace = true
