[package]
name = "hydir-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hydir"
path = "src/main.rs"

[dependencies]
hydir-backend = { path = "../hydir-backend" }
hydir-analysis = { path = "../hydir-analysis" }
hydir-core = { path = "../hydir-core" }
hydir-api = { path = "../hydir-api" }
eframe.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tonic.workspace = true
uuid.workspace = true
