[package]
name = "hydir-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hydir-core = { path = "../hydir-core" }
hydir-loader = { path = "../hydir-loader" }
hydir-semantics = { path = "../hydir-semantics" }
object.workspace = true
iced-x86.workspace = true
sha2.workspace = true
